### ISSUE TITLE
Не работает тестовая карта

### ISSUE THREAD

**Issue by virtualexx** [begateway/opencart-2.3-payment-module#1]
При попытке плтежа с данными тестовой карты, получаем на https://checkout.begateway.com/v2/result?token=...&uid=&status=error

Number is invalid,Unable to detect card type. Either the card number is incorrectly entered, or the card type is not supported.

**Comment by virtualexx** [comment]
![image](https://user-images.githubusercontent.com/16868550/48300719-85eeb680-e4f3-11e8-9593-24b1bfc363e9.png)

**Comment by avsh** [comment]
Проверьте, что прописали тестовую карту верно и не пропустили нолик. Карта рабочая и причина этой ошибки только в неверном вводе

**Comment by virtualexx** [comment]
Действительно. Возможно, проблема была в количестве символов номера карты. Этот сервис почему-то принимает больше, чем 16 символов. Первый раз с таким сталкиваюсь. Спасибо.

 

С уважением,

Алексей Новиков

**Comment by avsh** [comment]
19 цифр есть у карт маэстро, выпущенных в РФ. Да и спецификации платежных систем уже оперируют 19 цифрами
